### ISSUE TITLE
OPS20 - Demo Configuration - Teams Authentication

### ISSUE THREAD

**Issue by scubaninja** [microsoft/ignite-learning-paths-training-ops#68]
When configuring the demos for OPS20, the Logic App is configured with the default Ignite Teams tenant ID.  Authentication to this tenant fails.  Workaround:

1. Created new Teams site - example 'OPS20 Demo' under own tenant

2. Go into Logic App and change the tenant ID for both actions from the built in, to the ID of the newly created Team 'OPS20 Demo'

3. Re-authenticate - connectivity was then successful

**Comment by jasonhand** [comment]
Updates have been made to the post-deployment.md documentation to specify the need to create and use your own Microsoft Teams Tenant in the Logic App used in Demo 1
